server:
  port: 8080

spring:
  application:
    name: customerWebapp
  datasource:
    username: 'customer'
    url: jdbc:posgtresql://localhost:5432/customerwebapp
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show_sql: 'true'